./* This is the manual page of the task2(aka user manager.)
.TH task 2 "OS I - FCIH - 2016" "V1.0" "task2 manual page"

.SH NAME
tas2 - A userManager

.SH SYNOPSIS
task2

.SH DESCRIPTION
A simple user manager that add user,gruops delete user,groups in the system,also change user password, information and
add specific user to specific  groups

Through a user-friendly menu, you can choose between various options as mentioned above.

.SH OPTIONS
The menu interface is displayed by default and the program keeps running and re-displaying the menu interface until #6 is chosen.
 
.IP "Choice #1"
Add user or delete user
.IP "Choice #2"
Add group or delete group
.IP "Choice #3"
Change information of users
.IP "Choice #4"
Change account information
.IP "Choice #5"
Assign specific users to specific groups
.IP "Choice #6"
Exits the program.

.SH AUTHOR

Ahmed Ibrahim (20140009)

Eslam Ayman (20140080)

Marco Zakaria (20140290)

Mekhail maged (20140443)

Mina Atef (20140449)


